# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{create-rails-dev-db}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Burridge"]
  s.date = %q{2010-08-30}
  s.default_executable = %q{create-rails-dev-db}
  s.description = %q{This gem creates the database.yml file for a Rails app and creates the db in mysql and grants the permissions for the user.}
  s.email = %q{bburridg@gmail.com}
  s.executables = ["create-rails-dev-db"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/create-rails-dev-db",
     "config/database.yml",
     "create-rails-dev-db.gemspec",
     "lib/create-rails-dev-db.rb",
     "test/helper.rb",
     "test/test_create-rails-dev-db.rb"
  ]
  s.homepage = %q{http://github.com/bburridge/create-rails-dev-db}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{This gem creates the database.yml file for a Rails app and creates the db in mysql and grants the permissions for the user.}
  s.test_files = [
    "test/helper.rb",
     "test/test_create-rails-dev-db.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

